apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ${PROJECT_NAME}
  version: ${IMG_TAG}
  labels:
    app: ${PROJECT_NAME}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jenkins-sample
  template:
    metadata:
      labels:
        app: ${PROJECT_NAME}
    spec:
      containers: 
      - name: ${PROJECT_NAME}
        image: ${REGIS}:${IMG_TAG}
        ports:
        - containerPort: 80
      
